
GROQ_API_KEY="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"
LLAMA_CLOUD_API_KEY="llx-EiqX0AgjdKsS4MqFOhDr0vZUoLF1FdA0vx2H4IWnvIN4UG9b"
QDRANT_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.5whCg0JC864UhPjGxleaMRzOIt4i5Ti37Oeqpc3bxDA"
